### ISSUE TITLE
Compiler support

### ISSUE THREAD

**Issue by Anobium** [rallekralle11/Dact#1]
I am the key developer for Great Cow BASIC.  A very easy to compiler and tool chain.

This project makes a lot sense.  Well done.

I am willing to add this chip / solution to our compiler.  

When and how can I get a 2nd revision ( I think the 1st released has issues ) board ?

Evan

**Comment by rallekralle11** [comment]
no.

**Comment by Anobium** [comment]
No? 

What is the plan? Another revision ? No boards? Not interested in a wider development into other languages? 

Help me understand. Thanks.

**Comment by rallekralle11** [comment]
i will make other revisions, but i don't really know what you want with it.
it's an arduino nano, you can develop for that and it'll work on this

**Comment by Anobium** [comment]
Ok. The chip is a mega328a.  When you get another revision of the board then we could publish a set of demos for the board.
