### ISSUE TITLE
Suggestion: Use Resistor Arrays

### ISSUE THREAD

**Issue by nkappler** [rallekralle11/Dact#2]
In the readme you mentioned that you tried adding overvoltage protection for the 3V and 5V pins but it didn't fit.
You could try to use resistor arrays to reduce part count and make more space available...
![image](https://user-images.githubusercontent.com/9429273/218425079-82343abb-6d13-41f0-a165-268ce5007a60.png)

**Comment by rallekralle11** [comment]
thanks for the suggestion! it doesn't have too many resistors, but for the next version it might be a good idea

**Comment by nkappler** [comment]
I think there are array version of all sorts of components: capacitors, LEDs, diodes, etc...
Especially on the backside there seems to be a lot of repetition, so it might boil down the space requirements quite a bit :)

**Comment by rallekralle11** [comment]
if there are zener diode arrays that would help a lot. i'll look into it
